"""
extract_key_for_arduino.py
==========================
Reads walletA.priv and walletA.pub (generated by keygen.py) and prints
the C constants needed for the Arduino sketch.

Usage:
    python extract_key_for_arduino.py
"""

import textwrap
from pathlib import Path

WALLET = "walletA"   # change to walletB if needed

priv_bytes = Path(f"{WALLET}.priv").read_bytes()    # 32 bytes
pub_bytes  = Path(f"{WALLET}.pub").read_bytes()     # 64 bytes
pub_hex    = pub_bytes.hex()                         # 128 chars

assert len(priv_bytes) == 32, f"Expected 32-byte private key, got {len(priv_bytes)}"
assert len(pub_bytes)  == 64, f"Expected 64-byte public key, got {len(pub_bytes)}"


def to_c_array(name, size, data):
    hex_vals = ', '.join(f'0x{b:02X}' for b in data)
    lines = textwrap.wrap(hex_vals, width=56)
    body = ',\n  '.join(lines)
    return f"const uint8_t {name}[{size}] = {{\n  {body}\n}};"


print("=" * 70)
print(f"Paste these into your Arduino sketch (sensor_node.ino)")
print("=" * 70)
print()
print(to_c_array("PRIVATE_KEY", 32, priv_bytes))
print()
print(to_c_array("PUBLIC_KEY", 64, pub_bytes))
print()
print(f'// Hex-encoded public key — sent as "walletKey" in every JSON payload')
print(f'const char WALLET_KEY_HEX[] = "{pub_hex}";')
print()
print("=" * 70)
print(f"Wallet:    {WALLET}")
print(f"Public key (hex): {pub_hex}")
print("=" * 70)